<a href="https://colab.research.google.com/github/carighi/al_ml_workshop/blob/main/Numpy_Pandas/Exercise_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Convert list of dictionaries to Dataframe

In [1]:
import pandas as pd
d = [{'city':'Delhi',"data":1000}, {'city':'Bangalore',"data":2000},{'city':'Mumbai',"data":1000}]
d

[{'city': 'Delhi', 'data': 1000},
 {'city': 'Bangalore', 'data': 2000},
 {'city': 'Mumbai', 'data': 1000}]

In [ ]:
# Convert the list of dictionaries 'd' into a dataframe.
# Your code goes here

In [ ]:
# @title check answer here
df = pd.DataFrame(d)
df

#Convert CSV files to Dataframe

In [2]:
! pip install wget
! python -m wget "https://raw.githubusercontent.com/dipanjanS/practical-machine-learning-with-python/master/notebooks/Ch02_The_Python_ML_Ecosystem/simplemaps-worldcities-basic.csv" -o simplemaps-worldcities-basic.csv

Collecting wget
  Downloading wget-3.2.zip (10 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: wget
  Building wheel for wget (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9655 sha256=8dbaaeb5e970f87b8462b777c4c931fe652e89543c99381fc5608799af366aad
  Stored in directory: /root/.cache/pip/wheels/01/46/3b/e29ffbe4ebe614ff224bad40fc6a5773a67a163251585a13a9
Successfully built wget
Installing collected packages: wget
Successfully installed wget-3.2

Saved under simplemaps-worldcities-basic.csv

In [ ]:
# Download worldcities csv file
! pip install wget
! python -m wget "https://raw.githubusercontent.com/dipanjanS/practical-machine-learning-with-python/master/notebooks/Ch02_The_Python_ML_Ecosystem/simplemaps-worldcities-basic.csv" -o simplemaps-worldcities-basic.csv

# Read in csv file and convert it to dataframe called city_data

# <Your code goes here>

# Show the first 10 rows of converted dataframe
# <Your code goes here>

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: wget in /usr/local/lib/python3.7/dist-packages (3.2)

Saved under simplemaps-worldcities-basic (1).csv

In [7]:
# @title Check answer here
# Read in csv file and convert it to dataframe
city_data = pd.read_csv('simplemaps-worldcities-basic.csv')

# Show the first 10 rows of converted dataframe
city_data.head(n=10)

,city,city_ascii,lat,lng,pop,country,iso2,iso3,province
0,Qal eh-ye Now,Qal eh-ye,34.983000,63.133300,2997.0,Afghanistan,AF,AFG,Badghis
1,Chaghcharan,Chaghcharan,34.516701,65.250001,15000.0,Afghanistan,AF,AFG,Ghor
2,Lashkar Gah,Lashkar Gah,31.582998,64.360000,201546.0,Afghanistan,AF,AFG,Hilmand
3,Zaranj,Zaranj,31.112001,61.886998,49851.0,Afghanistan,AF,AFG,Nimroz
4,Tarin Kowt,Tarin Kowt,32.633298,65.866699,10000.0,Afghanistan,AF,AFG,Uruzgan
5,Zareh Sharan,Zareh Sharan,32.850000,68.416705,13737.0,Afghanistan,AF,AFG,Paktika
6,Asadabad,Asadabad,34.866000,71.150005,48400.0,Afghanistan,AF,AFG,Kunar
7,Taloqan,Taloqan,36.729999,69.540004,64256.0,Afghanistan,AF,AFG,Takhar
8,Mahmud-E Eraqi,Mahmud-E Eraqi,35.016696,69.333301,7407.0,Afghanistan,AF,AFG,Kapisa
9,Mehtar Lam,Mehtar Lam,34.650000,70.166701,17345.0,Afghanistan,AF,AFG,Laghman

#Data Access

##Head and Tail

Get the last 10 rows of **city_data**:

In [ ]:
# Your code goes here

In [ ]:
# @title Check answer here

# Show the last 10 rows of converted dataframe
city_data.tail(n=10)

##Slicing and Dicing

In [8]:
#Let's ge the column lat from city_data dataframe, and find out the type
series_es = city_data.lat
type(series_es)

pandas.core.series.Series

Get the first 8 rows of **series_es**:

In [ ]:
# Your code goes here

In [ ]:
# @title Check answer here
series_es[:8]

Get first 8 rows of **city_data**:

In [ ]:
# Your code goes here

In [ ]:
# @title Check answer here
city_data[:8]

Get the first 4 columns of the first 5 rows of **city_data**:

In [ ]:
# Your code goes here

In [ ]:
# @title Check answer here
city_data.iloc[:5, :4]

Select cities that have population of more than 10
million

In [ ]:
# Your code goes here

In [ ]:
# @title Check answer here
city_data[city_data['pop'] > 10000000]

#Data Operations

##Missing data and the fillna function

In [12]:
#Let's create a dataframe with random numbers and assign NaN to column C row indexed 4
import numpy as np
df = pd.DataFrame(np.random.randn(8, 3), columns=['A', 'B', 'C'])
df.iloc[4,2] = np.nan
df

          A         B         C
0 -1.833256 -0.603735 -1.056183
1  1.840020 -0.003348 -0.457218
2  1.140003  2.193637  0.362310
3  1.987613 -0.484313 -0.464515
4 -0.360856  0.300314       NaN
5 -0.924323 -0.627123 -0.956361
6  0.303999 -0.484191 -0.382157
7 -0.072677  0.287691 -1.756448

Replace all the "NaN" in **df** with "0":

In [ ]:
# Your code goes here

In [ ]:
# @title Check answer here
df.fillna(0)

#Descriptive Statistics functions

In [17]:
columns_numeric = ['lat','lng','pop']

['lat', 'lng', 'pop']

Get average 'lat', 'lng', and 'pop' values:

In [ ]:
# Your code goes here

In [ ]:
# @title Check answer here
city_data[columns_numeric].mean()

Get sum of 'lat', 'lng', and 'pop' values:

In [ ]:
# Your code goes here

In [ ]:
# @title Check answer here
city_data[columns_numeric].sum()

Get total number of 'lat', 'lng', and 'pop' values:

In [ ]:
# Your code goes here (hint: use count())

In [ ]:
# @title Check answer here
city_data[columns_numeric].count()

Get 75 percentile of 'lat', 'lng', and 'pop' values:

In [ ]:
# Your code goes here (hint: use quantile())

In [ ]:
# @title Check answer here
city_data[columns_numeric].quantile(0.75)

Get sums of each row:

In [ ]:
# Your code goes here

In [ ]:
# @title Check answer here
city_data[columns_numeric].sum(axis = 1)

Calculate
the most important statistics for numerical data in one go so that we don’t have to use individual functions:

In [ ]:
# Your code goes here

In [ ]:
# @title Check answer here
city_data[columns_numeric].describe()